# Generated for NaoQi method ALAudioDevice.openAudioInputs
# Opens the audio device for capture. If you closed the audio inputs with the closeAudioInputs method, you must call this method to be able to access to the sound data of the nao's microphones.

---


