# Generated for NaoQi method ALLauncher.launchLocal
# Loads dynamicaly a module

# the name of the modulePack to launch or the name of the python script to evaluate
string moduleName
---
# list of modules loaded
string[] value


