# Generated for NaoQi method ALMemory.getData
# Allows programs and modules to get data stored in ALMemory.

# Name of the data.
string name
---
# an array containing all the retrieved data
float32 value


