# Generated for NaoQi method ALMotion.stiffnessInterpolation
# Interpolates one or multiple joints to a target stiffness or along timed trajectories of stiffness. This is a blocking call.

# Name or names of joints, chains, "Body", "BodyJoints" or "BodyActuators".
string[] names
# An stiffness, list of stiffnesses or list of list of stiffnesses
float32[] stiffnessLists
# A time, list of times or list of list of times.
float32[] timeLists
---


