# Generated for NaoQi method ALSoundDetection.setParameterString
# DEPRECATED - Set detection parameters

# Name of detector. For now only one detector is available : "soundDetection/SoundDetector".
string type
# Name of the parameter. Please refer to the example below for the available parameters.
string paraDetect
# Value of the parameter.
float32 param
---


