/*
* Generated for ALPythonBridge, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALPythonBridgeEvalFull.h>
//#include <rosbridge/ALPythonBridgeEvalReturn.h>
//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>

//TEST(ALPythonBridge, evalFull) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALPythonBridgeEvalFull>(std::string("NaoQi/ALPythonBridge/evalFull"));
//  rosbridge::ALPythonBridgeEvalFull msg;
  //msg.stringToEvaluate = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALPythonBridge, evalReturn) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALPythonBridgeEvalReturn>(std::string("NaoQi/ALPythonBridge/evalReturn"));
//  rosbridge::ALPythonBridgeEvalReturn msg;
  //msg.stringToEvaluate = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALPythonBridge, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALPythonBridge/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.methodName = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALPythonBridge, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALPythonBridge/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


