/*
* Generated for ALAudioSourceLocalization, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALExtractorGetSubscribersInfo.h>

//TEST(ALAudioSourceLocalization, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALAudioSourceLocalization/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.methodName = ;

//  int result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALAudioSourceLocalization, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALAudioSourceLocalization/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  int result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALAudioSourceLocalization, getSubscribersInfo) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALExtractorGetSubscribersInfo>(std::string("NaoQi/ALAudioSourceLocalization/getSubscribersInfo"));
//  rosbridge::ALExtractorGetSubscribersInfo msg;


//  int result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


