/*
* Generated for ALVisionRecognition, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALExtractorGetSubscribersInfo.h>
//#include <rosbridge/ALVisionRecognitionSetParam.h>

//TEST(ALVisionRecognition, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALVisionRecognition/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.request.methodName = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALVisionRecognition, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALVisionRecognition/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALVisionRecognition, getSubscribersInfo) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALExtractorGetSubscribersInfo>(std::string("NaoQi/ALVisionRecognition/getSubscribersInfo"));
//  rosbridge::ALExtractorGetSubscribersInfo msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALVisionRecognition, setParam) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALVisionRecognitionSetParam>(std::string("NaoQi/ALVisionRecognition/setParam"));
//  rosbridge::ALVisionRecognitionSetParam msg;
  //msg.request.paramName = ;
  //msg.request.paramValue = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


