/*
* Generated for ALRobotPose, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALRobotPoseGetActualPoseAndTime.h>
//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALRobotPoseGetPoseNames.h>

//TEST(ALRobotPose, getActualPoseAndTime) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALRobotPoseGetActualPoseAndTime>(std::string("NaoQi/ALRobotPose/getActualPoseAndTime"));
//  rosbridge::ALRobotPoseGetActualPoseAndTime msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALRobotPose, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALRobotPose/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.request.methodName = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALRobotPose, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALRobotPose/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALRobotPose, getPoseNames) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALRobotPoseGetPoseNames>(std::string("NaoQi/ALRobotPose/getPoseNames"));
//  rosbridge::ALRobotPoseGetPoseNames msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


