/*
* Generated for ALSoundDetection, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALSoundDetectionGetDescription.h>
//#include <rosbridge/ALSoundDetectionGetEvents.h>
//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALExtractorGetSubscribersInfo.h>

//TEST(ALSoundDetection, getDescription) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALSoundDetectionGetDescription>(std::string("NaoQi/ALSoundDetection/getDescription"));
//  rosbridge::ALSoundDetectionGetDescription msg;
  //msg.request.type = ;
  //msg.request.nameDesc = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALSoundDetection, getEvents) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALSoundDetectionGetEvents>(std::string("NaoQi/ALSoundDetection/getEvents"));
//  rosbridge::ALSoundDetectionGetEvents msg;
  //msg.request.type = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALSoundDetection, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALSoundDetection/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.request.methodName = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALSoundDetection, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALSoundDetection/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALSoundDetection, getSubscribersInfo) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALExtractorGetSubscribersInfo>(std::string("NaoQi/ALSoundDetection/getSubscribersInfo"));
//  rosbridge::ALExtractorGetSubscribersInfo msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


