/*
* Generated for ALAudioPlayer, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>

//TEST(ALAudioPlayer, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALAudioPlayer/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.methodName = ;

//  int result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALAudioPlayer, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALAudioPlayer/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  int result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


