/*
* Generated for ALAudioDevice, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALAudioDeviceSendRemoteBufferToOutput.h>

//TEST(ALAudioDevice, getMethodHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetMethodHelp>(std::string("NaoQi/ALAudioDevice/getMethodHelp"));
//  rosbridge::ALModuleGetMethodHelp msg;
  //msg.methodName = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALAudioDevice, getModuleHelp) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALModuleGetModuleHelp>(std::string("NaoQi/ALAudioDevice/getModuleHelp"));
//  rosbridge::ALModuleGetModuleHelp msg;


//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}

//TEST(ALAudioDevice, sendRemoteBufferToOutput) {
//  ros::NodeHandle n;
//  ros::ServiceClient client = n.serviceClient<rosbridge::ALAudioDeviceSendRemoteBufferToOutput>(std::string("NaoQi/ALAudioDevice/sendRemoteBufferToOutput"));
//  rosbridge::ALAudioDeviceSendRemoteBufferToOutput msg;
  //msg.nbOfFrames = ;
  //msg.pBuffer = ;

//  bool result = client.call(msg);
//  ASSERT_EQ(result, true);
//}


