/*
* Generated for ALVideoDevice, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALVisionVideoInputGetDirectRawImageRemote.h>
//#include <rosbridge/ALVisionVideoInputGetImageRemote.h>
#include <rosbridge/ALModuleGetMethodHelp.h>
#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALVisionVideoInputResolutionToSizes.h>

