/*
* Generated for ALTextToSpeech, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);


