/*
* Generated for ALMotion, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool angleInterpolation(
//  rosbridge::ALMotionAngleInterpolation::Request  &req,
//  rosbridge::ALMotionAngleInterpolation::Response &res);

//bool angleInterpolationBezier(
//  rosbridge::ALMotionAngleInterpolationBezier::Request  &req,
//  rosbridge::ALMotionAngleInterpolationBezier::Response &res);

//bool angleInterpolationWithSpeed(
//  rosbridge::ALMotionAngleInterpolationWithSpeed::Request  &req,
//  rosbridge::ALMotionAngleInterpolationWithSpeed::Response &res);

//bool changeAngles(
//  rosbridge::ALMotionChangeAngles::Request  &req,
//  rosbridge::ALMotionChangeAngles::Response &res);

//bool getAngles(
//  rosbridge::ALMotionGetAngles::Request  &req,
//  rosbridge::ALMotionGetAngles::Response &res);

//bool getLimits(
//  rosbridge::ALMotionGetLimits::Request  &req,
//  rosbridge::ALMotionGetLimits::Response &res);

bool getMethodHelp(
  rosbridge::ALModuleGetMethodHelp::Request  &req,
  rosbridge::ALModuleGetMethodHelp::Response &res);

bool getModuleHelp(
  rosbridge::ALModuleGetModuleHelp::Request  &req,
  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool getRobotConfig(
//  rosbridge::ALMotionGetRobotConfig::Request  &req,
//  rosbridge::ALMotionGetRobotConfig::Response &res);

//bool getStiffnesses(
//  rosbridge::ALMotionGetStiffnesses::Request  &req,
//  rosbridge::ALMotionGetStiffnesses::Response &res);

//bool getTaskList(
//  rosbridge::ALMotionGetTaskList::Request  &req,
//  rosbridge::ALMotionGetTaskList::Response &res);

//bool getWalkArmsEnable(
//  rosbridge::ALMotionGetWalkArmsEnable::Request  &req,
//  rosbridge::ALMotionGetWalkArmsEnable::Response &res);

//bool positionInterpolation(
//  rosbridge::ALMotionPositionInterpolation::Request  &req,
//  rosbridge::ALMotionPositionInterpolation::Response &res);

//bool setAngles(
//  rosbridge::ALMotionSetAngles::Request  &req,
//  rosbridge::ALMotionSetAngles::Response &res);

//bool setMotionConfig(
//  rosbridge::ALMotionSetMotionConfig::Request  &req,
//  rosbridge::ALMotionSetMotionConfig::Response &res);

//bool setStiffnesses(
//  rosbridge::ALMotionSetStiffnesses::Request  &req,
//  rosbridge::ALMotionSetStiffnesses::Response &res);

//bool stiffnessInterpolation(
//  rosbridge::ALMotionStiffnessInterpolation::Request  &req,
//  rosbridge::ALMotionStiffnessInterpolation::Response &res);

//bool transformInterpolation(
//  rosbridge::ALMotionTransformInterpolation::Request  &req,
//  rosbridge::ALMotionTransformInterpolation::Response &res);

//bool wbSetEffectorControl(
//  rosbridge::ALMotionWbSetEffectorControl::Request  &req,
//  rosbridge::ALMotionWbSetEffectorControl::Response &res);


