/*
* Generated for ALLeds, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool fadeListRGB(
//  rosbridge::ALLedsFadeListRGB::Request  &req,
//  rosbridge::ALLedsFadeListRGB::Response &res);

//bool getIntensity(
//  rosbridge::ALLedsGetIntensity::Request  &req,
//  rosbridge::ALLedsGetIntensity::Response &res);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);


