/*
* Generated for ALMotion, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

#include <rosbridge/ALMotionAngleInterpolation.h>
//#include <rosbridge/ALMotionAngleInterpolationBezier.h>
#include <rosbridge/ALMotionAngleInterpolationWithSpeed.h>
#include <rosbridge/ALMotionChangeAngles.h>
#include <rosbridge/ALMotionGetAngles.h>
//#include <rosbridge/ALMotionGetLimits.h>
#include <rosbridge/ALModuleGetMethodHelp.h>
#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALMotionGetRobotConfig.h>
#include <rosbridge/ALMotionGetStiffnesses.h>
//#include <rosbridge/ALMotionGetTaskList.h>
#include <rosbridge/ALMotionGetWalkArmsEnable.h>
//#include <rosbridge/ALMotionPositionInterpolation.h>
#include <rosbridge/ALMotionSetAngles.h>
//#include <rosbridge/ALMotionSetMotionConfig.h>
#include <rosbridge/ALMotionSetStiffnesses.h>
#include <rosbridge/ALMotionStiffnessInterpolation.h>
//#include <rosbridge/ALMotionTransformInterpolation.h>
#include <rosbridge/ALMotionWbSetEffectorControl.h>

