/*
* Generated for ALMemory, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool dataChanged(
//  rosbridge::ALMotionRecorderDataChanged::Request  &req,
//  rosbridge::ALMotionRecorderDataChanged::Response &res);

//bool getDataString(
//  rosbridge::ALMemoryGetDataString::Request  &req,
//  rosbridge::ALMemoryGetDataString::Response &res);

//bool getData(
//  rosbridge::ALMemoryGetData::Request  &req,
//  rosbridge::ALMemoryGetData::Response &res);

//bool getDataListName(
//  rosbridge::ALMemoryGetDataListName::Request  &req,
//  rosbridge::ALMemoryGetDataListName::Response &res);

//bool getDataOnChange(
//  rosbridge::ALMemoryGetDataOnChange::Request  &req,
//  rosbridge::ALMemoryGetDataOnChange::Response &res);

//bool getListData(
//  rosbridge::ALMemoryGetListData::Request  &req,
//  rosbridge::ALMemoryGetListData::Response &res);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool insertDataObject(
//  rosbridge::ALMemoryInsertDataObject::Request  &req,
//  rosbridge::ALMemoryInsertDataObject::Response &res);

//bool insertListData(
//  rosbridge::ALMemoryInsertListData::Request  &req,
//  rosbridge::ALMemoryInsertListData::Response &res);

//bool insertObject(
//  rosbridge::ALMemoryInsertObject::Request  &req,
//  rosbridge::ALMemoryInsertObject::Response &res);

//bool raiseEvent(
//  rosbridge::ALMemoryRaiseEvent::Request  &req,
//  rosbridge::ALMemoryRaiseEvent::Response &res);

//bool raiseMicroEvent(
//  rosbridge::ALMemoryRaiseMicroEvent::Request  &req,
//  rosbridge::ALMemoryRaiseMicroEvent::Response &res);


