/*
* Generated for ALPreferences, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

bool getMethodHelp(
  rosbridge::ALModuleGetMethodHelp::Request  &req,
  rosbridge::ALModuleGetMethodHelp::Response &res);

bool getModuleHelp(
  rosbridge::ALModuleGetModuleHelp::Request  &req,
  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool readPrefFile(
//  rosbridge::ALPreferencesReadPrefFile::Request  &req,
//  rosbridge::ALPreferencesReadPrefFile::Response &res);

//bool saveToMemory(
//  rosbridge::ALPreferencesSaveToMemory::Request  &req,
//  rosbridge::ALPreferencesSaveToMemory::Response &res);

//bool writePrefFile(
//  rosbridge::ALPreferencesWritePrefFile::Request  &req,
//  rosbridge::ALPreferencesWritePrefFile::Response &res);


