/*
* Generated for ALPythonBridge, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool evalFull(
//  rosbridge::ALPythonBridgeEvalFull::Request  &req,
//  rosbridge::ALPythonBridgeEvalFull::Response &res);

//bool evalReturn(
//  rosbridge::ALPythonBridgeEvalReturn::Request  &req,
//  rosbridge::ALPythonBridgeEvalReturn::Response &res);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);


