/*
* Generated for ALBluetooth, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool getAssociatedDeviceList(
//  rosbridge::ALBluetoothGetAssociatedDeviceList::Request  &req,
//  rosbridge::ALBluetoothGetAssociatedDeviceList::Response &res);

//bool getDeviceList(
//  rosbridge::ALBluetoothGetDeviceList::Request  &req,
//  rosbridge::ALBluetoothGetDeviceList::Response &res);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool scan(
//  rosbridge::ALBluetoothScan::Request  &req,
//  rosbridge::ALBluetoothScan::Response &res);

//bool send(
//  rosbridge::ALBluetoothSend::Request  &req,
//  rosbridge::ALBluetoothSend::Response &res);

//bool setAssociatedDeviceList(
//  rosbridge::ALBluetoothSetAssociatedDeviceList::Request  &req,
//  rosbridge::ALBluetoothSetAssociatedDeviceList::Response &res);


