/*
* Generated for DCM, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool calibration(
//  rosbridge::DCMCalibration::Request  &req,
//  rosbridge::DCMCalibration::Response &res);

//bool createAlias(
//  rosbridge::DCMCreateAlias::Request  &req,
//  rosbridge::DCMCreateAlias::Response &res);

bool getMethodHelp(
  rosbridge::ALModuleGetMethodHelp::Request  &req,
  rosbridge::ALModuleGetMethodHelp::Response &res);

bool getModuleHelp(
  rosbridge::ALModuleGetModuleHelp::Request  &req,
  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool getPrefix(
//  rosbridge::DCMGetPrefix::Request  &req,
//  rosbridge::DCMGetPrefix::Response &res);

//bool preferences(
//  rosbridge::DCMPreferences::Request  &req,
//  rosbridge::DCMPreferences::Response &res);

//bool set(
//  rosbridge::DCMSet::Request  &req,
//  rosbridge::DCMSet::Response &res);

//bool setAlias(
//  rosbridge::DCMSetAlias::Request  &req,
//  rosbridge::DCMSetAlias::Response &res);


