/*
* Generated for ALVideoDevice, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool getDirectRawImageRemote(
//  rosbridge::ALVisionVideoInputGetDirectRawImageRemote::Request  &req,
//  rosbridge::ALVisionVideoInputGetDirectRawImageRemote::Response &res);

//bool getImageRemote(
//  rosbridge::ALVisionVideoInputGetImageRemote::Request  &req,
//  rosbridge::ALVisionVideoInputGetImageRemote::Response &res);

bool getMethodHelp(
  rosbridge::ALModuleGetMethodHelp::Request  &req,
  rosbridge::ALModuleGetMethodHelp::Response &res);

bool getModuleHelp(
  rosbridge::ALModuleGetModuleHelp::Request  &req,
  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool resolutionToSizes(
//  rosbridge::ALVisionVideoInputResolutionToSizes::Request  &req,
//  rosbridge::ALVisionVideoInputResolutionToSizes::Response &res);


