/*
* Generated for DCM, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/DCMCalibration.h>
#include <rosbridge/DCMCreateAlias.h>
#include <rosbridge/ALModuleGetMethodHelp.h>
#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/DCMGetPrefix.h>
//#include <rosbridge/DCMPreferences.h>
#include <rosbridge/DCMSet.h>
#include <rosbridge/DCMSetAlias.h>

