/*
* Generated for ALMemory, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALMotionRecorderDataChanged.h>
//#include <rosbridge/ALMemoryGetDataString.h>
//#include <rosbridge/ALMemoryGetData.h>
//#include <rosbridge/ALMemoryGetDataListName.h>
//#include <rosbridge/ALMemoryGetDataOnChange.h>
//#include <rosbridge/ALMemoryGetListData.h>
//#include <rosbridge/ALModuleGetMethodHelp.h>
//#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALMemoryInsertDataObject.h>
//#include <rosbridge/ALMemoryInsertListData.h>
//#include <rosbridge/ALMemoryInsertObject.h>
//#include <rosbridge/ALMemoryRaiseEvent.h>
//#include <rosbridge/ALMemoryRaiseMicroEvent.h>

