/*
* Generated for ALSentinel, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool BatteryChargeCellVoltageMinChanged(
//  rosbridge::ALSentinelBatteryChargeCellVoltageMinChanged::Request  &req,
//  rosbridge::ALSentinelBatteryChargeCellVoltageMinChanged::Response &res);

//bool BatteryChargeStatusChanged(
//  rosbridge::ALSentinelBatteryChargeStatusChanged::Request  &req,
//  rosbridge::ALSentinelBatteryChargeStatusChanged::Response &res);

bool getMethodHelp(
  rosbridge::ALModuleGetMethodHelp::Request  &req,
  rosbridge::ALModuleGetMethodHelp::Response &res);

bool getModuleHelp(
  rosbridge::ALModuleGetModuleHelp::Request  &req,
  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool onAccX(
//  rosbridge::ALSentinelOnAccX::Request  &req,
//  rosbridge::ALSentinelOnAccX::Response &res);

//bool onAccY(
//  rosbridge::ALSentinelOnAccY::Request  &req,
//  rosbridge::ALSentinelOnAccY::Response &res);

//bool onAccZ(
//  rosbridge::ALSentinelOnAccZ::Request  &req,
//  rosbridge::ALSentinelOnAccZ::Response &res);

//bool onBatteryMeasure(
//  rosbridge::ALSentinelOnBatteryMeasure::Request  &req,
//  rosbridge::ALSentinelOnBatteryMeasure::Response &res);

//bool onMotorError(
//  rosbridge::ALSentinelOnMotorError::Request  &req,
//  rosbridge::ALSentinelOnMotorError::Response &res);

//bool onTemperatureMeasure(
//  rosbridge::ALSentinelOnTemperatureMeasure::Request  &req,
//  rosbridge::ALSentinelOnTemperatureMeasure::Response &res);

//bool powerButtonOnPress(
//  rosbridge::ALSentinelPowerButtonOnPress::Request  &req,
//  rosbridge::ALSentinelPowerButtonOnPress::Response &res);


