/*
* Generated for ALSentinel, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

//#include <rosbridge/ALSentinelBatteryChargeCellVoltageMinChanged.h>
//#include <rosbridge/ALSentinelBatteryChargeStatusChanged.h>
#include <rosbridge/ALModuleGetMethodHelp.h>
#include <rosbridge/ALModuleGetModuleHelp.h>
//#include <rosbridge/ALSentinelOnAccX.h>
//#include <rosbridge/ALSentinelOnAccY.h>
//#include <rosbridge/ALSentinelOnAccZ.h>
//#include <rosbridge/ALSentinelOnBatteryMeasure.h>
//#include <rosbridge/ALSentinelOnMotorError.h>
//#include <rosbridge/ALSentinelOnTemperatureMeasure.h>
//#include <rosbridge/ALSentinelPowerButtonOnPress.h>

