/*
* Generated for ALMotionRecorder, then edited by hand for dynamic type methods
*
* Copyright (C) 2010 Aldebaran Robotics
*
*/

void bindCustomMethods(ALPtr<ALBroker> pNaoQiBroker, ros::NodeHandle& pRosNode);

//bool dataChanged(
//  rosbridge::ALMotionRecorderDataChanged::Request  &req,
//  rosbridge::ALMotionRecorderDataChanged::Response &res);

//bool getMethodHelp(
//  rosbridge::ALModuleGetMethodHelp::Request  &req,
//  rosbridge::ALModuleGetMethodHelp::Response &res);

//bool getModuleHelp(
//  rosbridge::ALModuleGetModuleHelp::Request  &req,
//  rosbridge::ALModuleGetModuleHelp::Response &res);

//bool startPeriodicRecording(
//  rosbridge::ALMotionRecorderStartPeriodicRecording::Request  &req,
//  rosbridge::ALMotionRecorderStartPeriodicRecording::Response &res);

//bool stopAndGetRecording(
//  rosbridge::ALMotionRecorderStopAndGetRecording::Request  &req,
//  rosbridge::ALMotionRecorderStopAndGetRecording::Response &res);


